// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALxE0lWVUc9AjTAAhDB4ofXXiPbOuE9xQ',
    appId: '1:1005254697426:web:d894ec055d5b4bc358a80b',
    messagingSenderId: '1005254697426',
    projectId: 'apexology',
    authDomain: 'apexology.firebaseapp.com',
    storageBucket: 'apexology.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBpH-t5c_RNohfAINX-qBsm_aFl3rL1Sw',
    appId: '1:1005254697426:android:a2fe28a1b58a7a9958a80b',
    messagingSenderId: '1005254697426',
    projectId: 'apexology',
    storageBucket: 'apexology.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOtPLPfsIyfMRKJwlKLdZyMmgNx0jEkPY',
    appId: '1:1005254697426:ios:66653dc21da443b058a80b',
    messagingSenderId: '1005254697426',
    projectId: 'apexology',
    storageBucket: 'apexology.appspot.com',
    iosClientId: '1005254697426-015f2jctnivq1ei4nrfke3ktvvji6ei4.apps.googleusercontent.com',
    iosBundleId: 'com.example.apexology',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOtPLPfsIyfMRKJwlKLdZyMmgNx0jEkPY',
    appId: '1:1005254697426:ios:66653dc21da443b058a80b',
    messagingSenderId: '1005254697426',
    projectId: 'apexology',
    storageBucket: 'apexology.appspot.com',
    iosClientId: '1005254697426-015f2jctnivq1ei4nrfke3ktvvji6ei4.apps.googleusercontent.com',
    iosBundleId: 'com.example.apexology',
  );
}
